# Generated by Django 2.2 on 2020-03-10 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas_app', '0002_auto_20200310_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ninja',
            name='dojo_id',
        ),
    ]
